import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

/**
 * 🔄 Project: Sync Protocol
 * -------------------------------------------------------------------------
 * Synchronizes ignore files with the master source of truth.
 * Source: ignores.master.json
 * Targets: .gitignore, .prettierignore, .stylelintignore
 * -------------------------------------------------------------------------
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(__dirname, "../../../..")

const MASTER_PATH = path.join(REPO_ROOT, "ignores.master.json")
const HEADER =
    "# Generated by Project Sync (.agent/skills/project/scripts/sync.js) – DO NOT EDIT.\n"

/**
 * Reads and parses JSON safely.
 */
function readJson(filePath) {
    if (!fs.existsSync(filePath)) return null
    try {
        const content = fs.readFileSync(filePath, "utf8")
        return JSON.parse(content)
    } catch (e) {
        console.error(`❌ Failed to parse JSON: ${filePath}`, e.message)
        return null
    }
}

/**
 * Writes text to a file, ensuring directory existence.
 */
function writeText(filePath, content) {
    const dir = path.dirname(filePath)
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
    fs.writeFileSync(filePath, content, "utf8")
    console.log(`   📝 Wrote ${path.relative(REPO_ROOT, filePath)}`)
}

function sync() {
    console.log("\n🛡️  Syncing Ignores...")

    const master = readJson(MASTER_PATH)
    if (!master) {
        console.error(
            "   ❌ Aborting: ignores.master.json not found or invalid."
        )
        process.exit(1)
    }

    // 1. Generate .gitignore
    if (Array.isArray(master.gitignore)) {
        writeText(
            path.join(REPO_ROOT, ".gitignore"),
            HEADER + master.gitignore.join("\n") + "\n"
        )
    }

    // 2. Generate linter ignores
    const targetLinters = ["prettier", "stylelint"]
    if (master.linters) {
        for (const linter of targetLinters) {
            if (Array.isArray(master.linters[linter])) {
                writeText(
                    path.join(REPO_ROOT, `.${linter}ignore`),
                    HEADER + master.linters[linter].join("\n") + "\n"
                )
            }
        }
    }

    console.log("\n✨ Sync complete.\n")
}

sync()
