#!/usr/bin/env node

/**
 * 🔄 Gamemaster: Sync Protocol
 * -------------------------------------------------------------------------
 * Synchronizes configuration pillars (MCP, Ignores, Colors) with local state.
 * Called by: .agent/skills/gamemaster/scripts/gamemaster.js
 * -------------------------------------------------------------------------
 */

import fs from "fs"
import os from "os"
import path from "path"
import { fileURLToPath } from "url"

// ESM Directory Fix
const __dirname = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(__dirname, "../../../..")

const IS_JSON = process.argv.includes("--json")

// --- 🛠️ Helpers ---

const robotLog = (...args) => {
    if (!IS_JSON) console.log(...args)
}

const robotError = (...args) => {
    console.error(...args)
}

// Try to load .env
let dotenv
try {
    dotenv = await import("dotenv")
} catch {
    // Optional dependency
}

function readJson(filePath) {
    if (!fs.existsSync(filePath)) return {}
    try {
        let content = fs.readFileSync(filePath, "utf8")
        // Remove BOM if present
        if (content.charCodeAt(0) === 0xfeff) content = content.slice(1)
        return JSON.parse(content || "{}")
    } catch (e) {
        robotError(`❌ Failed to parse JSON: ${filePath}`, e.message)
        return {}
    }
}

function writeJson(filePath, data) {
    const dir = path.dirname(filePath)
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + "\n", "utf8")
    robotLog(`   📝 Wrote ${path.relative(REPO_ROOT, filePath)}`)
}

function writeText(filePath, content) {
    const dir = path.dirname(filePath)
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
    fs.writeFileSync(filePath, content, "utf8")
    robotLog(`   📝 Wrote ${path.relative(REPO_ROOT, filePath)}`)
}

// --- 🔄 Sync Functions ---

/**
 * 1. Sync Ignore Files
 * Generates .gitignore, .eslintignore, etc. from ignores.master.json
 */
function syncIgnores() {
    robotLog("\n🛡️  Syncing Ignores...")
    const masterPath = path.join(REPO_ROOT, "ignores.master.json")
    if (!fs.existsSync(masterPath))
        return robotLog("   ⚠️  No ignores.master.json found.")

    const master = readJson(masterPath)
    const header = "# Generated by Gamemaster (sync.js) – DO NOT EDIT.\n"

    // 1. Linters
    if (master.linters) {
        for (const [key, patterns] of Object.entries(master.linters)) {
            // Special Case: Markdownlint config
            if (key === "markdownlint") {
                const cfgPath = path.join(REPO_ROOT, ".markdownlint-cli2.jsonc")
                const cfg = readJson(cfgPath)
                cfg.ignores = Array.from(new Set(patterns)).sort()
                writeJson(cfgPath, cfg)
                continue
            }

            // Standard .{name}ignore files
            const ignoreFile = path.join(REPO_ROOT, `.${key}ignore`)
            writeText(ignoreFile, header + patterns.join("\n") + "\n")
        }
    }

    // 2. Gitignore
    if (master.gitignore) {
        const gitPath = path.join(REPO_ROOT, ".gitignore")
        writeText(gitPath, header + master.gitignore.join("\n") + "\n")
    }

    // 3. VS Code Settings
    if (master.vscode) {
        const vsPath = path.join(REPO_ROOT, ".vscode/settings.json")
        const vsSettings = readJson(vsPath)
        Object.assign(vsSettings, master.vscode)
        writeJson(vsPath, vsSettings)
    }
}

/**
 * 2. Sync MCP Servers
 * Source of truth: ~/.gemini/antigravity/mcp_config.json (Antigravity UI)
 * Targets: mcp.json (repo) and .gemini/settings.json (Gemini CLI)
 */
function syncMcp() {
    robotLog("\n🔌 Syncing MCP Config...")
    const masterPath = path.join(
        os.homedir(),
        ".gemini",
        "antigravity",
        "mcp_config.json"
    )

    if (!fs.existsSync(masterPath)) {
        return robotLog(
            "   ⚠️  No ~/.gemini/antigravity/mcp_config.json found."
        )
    }

    const master = readJson(masterPath)

    // Write standard mcp.json
    writeJson(path.join(REPO_ROOT, "mcp.json"), master)

    // Update Gemini Settings
    const geminiPath = path.join(REPO_ROOT, ".gemini/settings.json")
    if (fs.existsSync(geminiPath)) {
        const settings = readJson(geminiPath)
        const servers = {}

        // Transform for Gemini format (expects 'url' not 'serverUrl')
        for (const [name, cfg] of Object.entries(master.mcpServers || {})) {
            if (cfg.disabled) continue
            servers[name] = { ...cfg }
            if (servers[name].serverUrl) {
                servers[name].url = servers[name].serverUrl
                delete servers[name].serverUrl
            }
            delete servers[name].disabled
        }

        settings.mcpServers = servers
        writeJson(geminiPath, settings)
    }
}

/**
 * 3. Sync Design Tokens (Colors)
 * Extracts palette from config.js -> _variables.scss
 */
function syncColors() {
    robotLog("\n🎨 Syncing Chalk Regime Colors...")
    const configPath = path.join(REPO_ROOT, "src/core/engine/config.js")
    const scssPath = path.join(REPO_ROOT, "src/theme/abstracts/_variables.scss")

    if (!fs.existsSync(configPath) || !fs.existsSync(scssPath)) {
        return robotLog("   ⚠️  Missing config.js or _variables.scss")
    }

    const jsContent = fs.readFileSync(configPath, "utf8")
    const match = jsContent.match(/PALETTE:\s*\{([^}]+)\}/s)
    if (!match) return

    // Extract Colors
    const colors = {}
    const regex = /(\w+):\s*["']([^"']+)["']/g
    let m
    while ((m = regex.exec(match[1])) !== null) {
        colors[m[1]] = m[2]
    }

    // Replace in SCSS
    let scss = fs.readFileSync(scssPath, "utf8")
    let count = 0

    for (const [name, hex] of Object.entries(colors)) {
        if (name === "default") continue
        const varName = `\\$signature-${name}` // Matches $signature-aura, etc.
        const replaceRegex = new RegExp(`(${varName}:\\s*)#[0-9a-fA-F]{6}`, "g")

        if (replaceRegex.test(scss)) {
            scss = scss.replace(replaceRegex, `$1${hex}`)
            count++
        }
    }

    if (count > 0) {
        fs.writeFileSync(scssPath, scss, "utf8")
        robotLog(`   ✅ Updated ${count} variables.`)
    } else {
        robotLog("   ✨ Colors up to date.")
    }
}

// --- 🚀 Execution ---

async function main() {
    const args = process.argv.slice(2)

    // Parse simplified flags
    const runAll = args.includes("--all")
    const runIgnores = runAll || args.includes("--ignores")
    const runMcp = runAll || args.includes("--mcp")
    const runColors = runAll || args.includes("--colors")

    if (runIgnores) syncIgnores()
    if (runMcp) syncMcp()
    if (runColors) syncColors()

    if (IS_JSON) {
        console.log(JSON.stringify({ status: "success" }))
    }
}

main().catch((err) => {
    if (IS_JSON) {
        console.log(JSON.stringify({ status: "error", message: err.message }))
    } else {
        console.error("❌ Sync Fatal Error:", err)
    }
    process.exit(1)
})
