#!/usr/bin/env node

import { execSync } from "child_process"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

// ESM replacement for __dirname
const __dirname = path.dirname(fileURLToPath(import.meta.url))

const IS_JSON = process.argv.includes("--json")

const robotLog = (...args) => {
    if (IS_JSON) {
        console.error(...args)
    } else {
        console.log(...args)
    }
}

// Try to import dotenv if available
let dotenv
try {
    // Use dynamic import for optional dependency
    dotenv = await import("dotenv")
} catch {
    // dotenv might not be installed in all environments
}

// --- GENERIC SETUP & UTILITIES ---
const REPO_ROOT = path.resolve(__dirname, "../../../..")

function readJson(filePath) {
    if (!fs.existsSync(filePath)) {
        console.warn(
            `⚠️  File not found: ${path.relative(
                REPO_ROOT,
                filePath
            )}. Returning empty object.`
        )
        return {}
    }
    try {
        let content = fs.readFileSync(filePath, "utf8")
        if (content.trim() === "") {
            console.warn(
                `⚠️  File is empty: ${path.relative(
                    REPO_ROOT,
                    filePath
                )}. Returning empty object.`
            )
            return {}
        }
        if (content.charCodeAt(0) === 0xfeff) content = content.slice(1)
        return JSON.parse(content)
    } catch {
        console.error(
            `❌  Could not parse JSON from ${path.relative(
                REPO_ROOT,
                filePath
            )}. Returning empty object.`
        )
        return {}
    }
}

function writeJson(filePath, data) {
    const dir = path.dirname(filePath)
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + "\n", "utf8")
    robotLog(`📝 Wrote ${path.relative(REPO_ROOT, filePath)}`)
}

function writeTextFile(filePath, content) {
    const dir = path.dirname(filePath)
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
    fs.writeFileSync(filePath, content, "utf8")
    robotLog(`📝 Wrote ${path.relative(REPO_ROOT, filePath)}`)
}

// --- SYNC LIBS LOGIC ---
// --- SYNC LIBS LOGIC ---
// (Legacy: Removed in favor of npm)
// async function syncLibs() { ... }

// --- SYNC IGNORES LOGIC ---
// --- SYNC IGNORES LOGIC ---
function syncIgnores() {
    robotLog("\n🔄 Syncing ignore files...")
    const masterIgnoresPath = path.join(REPO_ROOT, "ignores.master.json")
    const jsconfigPath = path.join(REPO_ROOT, "jsconfig.json")
    const settingsPath = path.join(REPO_ROOT, ".vscode", "settings.json")

    const masterIgnores = readJson(masterIgnoresPath)
    if (Object.keys(masterIgnores).length === 0) return

    const header = "# Generated by scripts/sync.js – do not edit.\n"

    // Dynamic generation of ignore files from linters object
    if (masterIgnores.linters) {
        for (const [linterKey, patterns] of Object.entries(
            masterIgnores.linters
        )) {
            // Special handling for markdownlint which uses a config file instead of .ignore file
            if (linterKey === "markdownlint") {
                const markdownlintConfigPath = path.join(
                    REPO_ROOT,
                    ".markdownlint-cli2.jsonc"
                )
                const markdownlintConfig = readJson(markdownlintConfigPath)
                markdownlintConfig.ignores = Array.from(
                    new Set([...(patterns || [])])
                ).sort()
                writeJson(markdownlintConfigPath, markdownlintConfig)
                continue
            }

            // For all other linters, create a .{linter}ignore file
            // e.g. eslint -> .eslintignore, prettier -> .prettierignore
            const ignoreFileName = `.${linterKey}ignore`
            writeTextFile(
                path.join(REPO_ROOT, ignoreFileName),
                header + (patterns || []).join("\n") + "\n"
            )
        }
    }

    // Handle .gitignore explicitly as it's at the root level, not under linters
    if (masterIgnores.gitignore) {
        writeTextFile(
            path.join(REPO_ROOT, ".gitignore"),
            header + (masterIgnores.gitignore || []).join("\n") + "\n"
        )
    }

    const jsconfig = readJson(jsconfigPath)
    jsconfig.compilerOptions = jsconfig.compilerOptions || {}
    jsconfig.exclude = Array.from(
        new Set(["node_modules", ...(masterIgnores.gitignore || [])])
    ).sort()
    writeJson(jsconfigPath, jsconfig)

    const settings = readJson(settingsPath)

    // Merge all settings from masterIgnores.vscode into the actual settings
    // This allows controlling any VS Code setting from ignores.master.json
    if (masterIgnores.vscode) {
        Object.assign(settings, masterIgnores.vscode)
    }

    writeJson(settingsPath, settings)

    robotLog("✅ Ignore files sync process complete.")
}

// --- SYNC MCP LOGIC ---
function syncMcp() {
    robotLog("\n🔄 Syncing MCP configurations...")
    const masterMcpPath = path.join(REPO_ROOT, "mcp.master.json")
    const envPath = path.join(REPO_ROOT, ".env")
    const geminiSettingsPath = path.join(REPO_ROOT, ".gemini", "settings.json")

    const masterMcp = readJson(masterMcpPath)
    if (Object.keys(masterMcp).length === 0) return

    const envMap =
        fs.existsSync(envPath) && dotenv
            ? {
                  ...process.env,
                  ...dotenv.default.parse(fs.readFileSync(envPath)),
              } // Note: dotenv.default for ESM default import
            : { ...process.env }

    const substituteEnvVariables = (obj) =>
        JSON.parse(
            JSON.stringify(obj).replace(
                /\$\{([A-Za-z_][A-Za-z0-9_]*)\}/g,
                (match, key) => envMap[key] || match
            )
        )

    const resolvedMcp = substituteEnvVariables(masterMcp)

    // 1. Write to mcp.json (for generic usage - keep original format)
    writeJson(path.join(REPO_ROOT, "mcp.json"), resolvedMcp)

    // 2. Update .gemini/settings.json (with Gemini-specific transformations)
    if (fs.existsSync(geminiSettingsPath)) {
        robotLog(
            `  Updating ${path.relative(REPO_ROOT, geminiSettingsPath)}...`
        )
        try {
            const geminiSettings = readJson(geminiSettingsPath)

            if (resolvedMcp.mcpServers) {
                const geminiMcpServers = {}

                for (const [name, config] of Object.entries(
                    resolvedMcp.mcpServers
                )) {
                    // Skip disabled servers
                    if (config.disabled === true) {
                        continue
                    }

                    const newConfig = { ...config }

                    // Remove keys not supported by Gemini CLI
                    delete newConfig.disabled
                    delete newConfig.disabledTools

                    // Rename serverUrl to url (Gemini expects 'url' for SSE)
                    if (newConfig.serverUrl) {
                        newConfig.url = newConfig.serverUrl
                        delete newConfig.serverUrl
                    }

                    geminiMcpServers[name] = newConfig
                }

                geminiSettings.mcpServers = geminiMcpServers
                writeJson(geminiSettingsPath, geminiSettings)
                robotLog(
                    `  ✅ Updated mcpServers in .gemini/settings.json (with adaptations)`
                )
            } else {
                robotLog(
                    `  ⚠️ No mcpServers found in master config, skipping .gemini/settings.json update`
                )
            }
        } catch (err) {
            console.error(
                `  ❌ Failed to update .gemini/settings.json: ${err.message}`
            )
        }
    } else {
        robotLog(
            `  Reference to .gemini/settings.json not found, skipping update.`
        )
    }

    robotLog("✅ MCP sync complete.")
}

// --- SYNC MCP TO CLAUDE CODE CLI ---
function syncMcpToClaudeCode() {
    robotLog("\n🔄 Syncing MCP servers to Claude Code CLI...")
    const mcpJsonPath = path.join(REPO_ROOT, "mcp.json")

    if (!fs.existsSync(mcpJsonPath)) {
        robotLog("⚠️  mcp.json not found. Run sync:mcp first.")
        return
    }

    const mcpConfig = readJson(mcpJsonPath)
    const servers = mcpConfig.mcpServers || {}

    if (Object.keys(servers).length === 0) {
        robotLog("⚠️  No MCP servers found in mcp.json")
        return
    }

    let successCount = 0
    let existsCount = 0
    let failCount = 0

    for (const [name, config] of Object.entries(servers)) {
        try {
            robotLog(`  Adding ${name}...`)
            const jsonString = JSON.stringify(config)
            const command = `claude mcp add-json "${name}" ${JSON.stringify(
                jsonString
            )}`
            execSync(command, { stdio: "pipe" })

            successCount++
            robotLog(`    ✅ Added`)
        } catch (error) {
            const errorMsg = error.message || ""
            if (errorMsg.includes("already exists")) {
                existsCount++
                robotLog(`    ⏭️  Already exists (skipped)`)
            } else {
                failCount++
                console.error(`    ❌ Failed:`, errorMsg.split("\n")[0])
            }
        }
    }

    robotLog(
        `\n✅ Complete: ${successCount} added, ${existsCount} already existed, ${failCount} failed`
    )

    if (failCount === 0) {
        robotLog("🎉 All MCP servers synced to Claude Code CLI!")
        robotLog("   Restart Claude Code to see the changes.")
    } else {
        robotLog(
            "⚠️  Some servers failed. Check errors above and add manually if needed."
        )
    }
}

// --- SYNC COLORS FROM config.js TO _variables.scss ---
function syncColors() {
    robotLog(
        "\n🎨 Syncing signature colors from config.js to _variables.scss..."
    )

    const configPath = path.join(REPO_ROOT, "src/gamemaster/config.js")
    const scssPath = path.join(
        REPO_ROOT,
        "src/mesmer/scss/abstracts/_variables.scss"
    )

    if (!fs.existsSync(configPath)) {
        console.error("❌ config.js not found")
        return
    }

    if (!fs.existsSync(scssPath)) {
        console.error("❌ _variables.scss not found")
        return
    }

    // Read config.js and extract PALETTE
    const configContent = fs.readFileSync(configPath, "utf8")
    const paletteMatch = configContent.match(/PALETTE:\s*\{([^}]+)\}/s)

    if (!paletteMatch) {
        console.error("❌ Could not find PALETTE in config.js")
        return
    }

    // Parse palette entries: key: "value" or key: "#value"
    const paletteEntries = {}
    const entryRegex = /(\w+):\s*["']([^"']+)["']/g
    let match
    while ((match = entryRegex.exec(paletteMatch[1])) !== null) {
        paletteEntries[match[1]] = match[2]
    }

    robotLog(`  Found ${Object.keys(paletteEntries).length} palette colors`)

    // Read SCSS and update signature colors
    let scssContent = fs.readFileSync(scssPath, "utf8")

    // Update each signature color variable
    let updatedCount = 0
    for (const [name, hex] of Object.entries(paletteEntries)) {
        if (name === "default") continue // Skip default, it's an alias

        const varName = `$signature-${name}`
        const regex = new RegExp(`(\\${varName}:\\s*)#[0-9a-fA-F]{6}`, "g")

        if (regex.test(scssContent)) {
            scssContent = scssContent.replace(regex, `$1${hex}`)
            updatedCount++
        }
    }

    if (updatedCount > 0) {
        fs.writeFileSync(scssPath, scssContent, "utf8")
        robotLog(
            `✅ Updated ${updatedCount} signature colors in _variables.scss`
        )
    } else {
        robotLog("ℹ️  No colors needed updating (already in sync)")
    }
}
async function main() {
    /** @type {Record<string, any>} */
    const args = process.argv.slice(2).reduce((acc, arg) => {
        if (arg === "--json") return acc // Skip json flag in parsed args
        const [key, value] = arg.split("=")
        acc[key.replace("--", "")] = value === undefined ? true : value
        return acc
    }, {})

    const runAll = args.all || Object.keys(args).length === 0

    // if (runAll || args.libs) await syncLibs() // Removed legacy libs sync

    if (runAll || args.ignores) syncIgnores()
    if (runAll || args.mcp) syncMcp()
    if (runAll || args.colors) syncColors()
    if (args.claude) syncMcpToClaudeCode()

    if (IS_JSON) {
        console.log(
            JSON.stringify({ status: "success", operations: Object.keys(args) })
        )
    }
}

main().catch((err) => {
    console.error("❌ An error occurred during the sync process:", err)
    process.exit(1)
})
