/**
 * @file simulation-audit.js
 * 📊 THE DASHBOARD: High-Fidelity Technical Reporter.
 *
 * NOTE: This script is executed via Vitest to handle Svelte/ESM/Rune dependencies.
 * Run with: npx vitest run .agents/skills/simulation/scripts/simulation-audit.js
 */

import fs from "fs";
import { describe, it } from "vitest";
import { SimulationSimulation } from "./simulation-simulation.js";

describe("🕹️ SYSTEM TURN: Source Audit", () => {
  it("executes the 'Gothic Trial' baseline and generates an audit report", async () => {
    // 1. DEFINE SCENARIO (Gothic Block Baseline)
    const scenario = {
      ai_id: "lord-valerius",
      user_id: "caelum",
      fractal_id: "ashen-weald",
      history: [
        {
          role: "ai",
          character_name: "Lord Valerius",
          text: "You stumble through the ash, little bird. Do you seek sanctuary or a cage?",
          type: "dialogue",
        },
      ],
    };

    const input = "I offer no resistance, only a silent plea for protection from the dark.";

    // 2. RUN THE DRIVETRAIN
    console.log("🚀 [AUDIT] Launching Simulation-Simulation...");
    const result = await SimulationSimulation.execute_turn(input, scenario);

    // 3. GENERATE REPORT
    const SEP = "────────────────────────────────────────────────────────────────────────────────";
    const timestamp = new Date()
      .toLocaleString("sv-SE", { timeZone: "Europe/Stockholm" })
      .replace(/T/, " ");

    const report = `# 📊 Simulation Audit Report

**Timestamp:** \`${timestamp}\`
**Round:** \`${result.payload.round}\`

${SEP}

## [PHASE 1: THE KERNEL (HYDRATION)]

- **Input:** "${input}"
- **Scenario:** Gothic Baseline (Valerius / Caelum / Ashen Weald)
- **Entities Loaded:** ${Object.keys(result.payload.entities).join(", ")}

${SEP}

## [PHASE 2: THE ECHO (DYNAMICS)]

- **Signal Prompts:** ${result.snapshot.signal_prompts.join(", ") || "None"}
- **Mechanical Weights:**
  - **AI (Intensity):** \`${result.snapshot.ai?.dynamics?.intensity || 50}\`
  - **Fractal (Entropy):** \`${result.snapshot.fractal?.dynamics?.entropy || 50}\`
- **Logic Flags:** ${result.snapshot.flags?.join(", ") || "None"}

${SEP}

## [PHASE 3: THE SYNTHESIS (PROMPT)]

\`\`\`xml
${result.system}
\`\`\`

${SEP}

> [!NOTE]
> This audit was generated by the **Simulation-Simulation** drivetrain.
> All dynamics and flags are derived from Rule 02 and Rule 03 physics boundaries.
`;

    // 4. PERSISTENCE
    console.log(report);
    fs.writeFileSync("tmp/audit_report.md", report);
    console.log("✅ Audit report synthesized: tmp/audit_report.md");
  });
});
