/**
 * @file simulation-audit.test.js
 * 📊 THE DASHBOARD: High-Fidelity Technical Reporter.
 *
 * NOTE: This script is executed via Vitest to handle Svelte/ESM/Rune dependencies.
 * Run with: npx vitest run .agents/skills/simulation/scripts/simulation-audit.test.js
 */

import fs from "fs";
import { describe, it, expect } from "vitest";
import { SimulationAudit } from "./simulation-audit.js";

describe("🕹️ SYSTEM TURN: Source Audit", () => {
  it("executes the 'Gothic Trial' baseline and generates an audit report", async () => {
    const scenario = {
      ai_id: "silvers",
      user_id: "julien",
      fractal_id: "ashenweald",
      history: [
        {
          role: "model",
          content: "You stumble through the ash, little bird. Do you seek sanctuary or a cage?",
          character_name: "Lord Valerius",
        },
      ],
    };

    const input = "I offer no resistance, only a silent plea for protection from the dark.";

    console.log("🚀 [AUDIT] Launching SimulationAudit...");
    const result = await SimulationAudit.execute_turn(input, scenario);

    // 3. GENERATE REPORT
    const SEP = "────────────────────────────────────────────────────────────────────────────────";
    const timestamp = new Date().toLocaleString("sv-SE", { timeZone: "Europe/Stockholm" }).replace(/T/, " ");

    const verificationSummary =
      result.verification.failed.length === 0
        ? `✅ All ${result.verification.passed.length} pipeline checks passed`
        : `⚠️ ${result.verification.passed.length} passed, ${result.verification.failed.length} failed:\n${result.verification.failed.map((f) => `   - ${f}`).join("\n")}`;

    const report = `# 📊 Simulation Audit Report

**Timestamp:** \`${timestamp}\`
**Round:** \`${result.payload.round}\`

${SEP}

## [PHASE 1: THE KERNEL (HYDRATION)]

- **Input:** "${input}"
- **Scenario:** Gothic Baseline (Valerius / Caelum / Ashenweald)
- **Entities Loaded:** ${Object.keys(result.payload.entities).join(", ")}

${SEP}

## [PHASE 2: DIRECTOR PROMPT (Shot 1)]

\`\`\`xml
${result.director_prompt}
\`\`\`

### Director Task

\`\`\`xml
${result.director_task}
\`\`\`

${SEP}

## [PHASE 3: CHARACTER PROMPT (Shot 2)]

\`\`\`xml
${result.character_prompt}
\`\`\`

### Character Task

\`\`\`xml
${result.character_task}
\`\`\`

${SEP}

## [PHASE 4: PIPELINE VERIFICATION]

${verificationSummary}

**Passed Checks:**
${result.verification.passed.map((c) => `- [x] ${c}`).join("\n")}

${result.verification.failed.length > 0 ? "**Failed Checks:**\n" + result.verification.failed.map((c) => `- [ ] ${c}`).join("\n") : ""}

${SEP}

> [!NOTE]
> This audit was generated by the **SimulationAudit** drivetrain.
> All dynamics and flags are derived from Rule 02 and Rule 03 physics boundaries.
> Pipeline verification covers: evidence_classification, COGNITIVE_STATE,
> ACTIVE_GOALS, FUTURE_ATMOSPHERE, prefix-cache separation, and epistemic physics.
`;

    fs.mkdirSync("tmp", { recursive: true });
    fs.writeFileSync("tmp/audit_report.md", report);
    console.log("✅ Audit report synthesized: tmp/audit_report.md");

    // 5. VERIFICATION — Prompts are generated
    expect(result.director_prompt).toBeDefined();
    expect(result.director_task).toBeDefined();
    expect(result.character_prompt).toBeDefined();
    expect(result.character_task).toBeDefined();
  });

  it("Character prompt keeps dynamics in task snapshot", async () => {
    const scenario = {
      ai_id: "silvers",
      user_id: "julien",
      fractal_id: "ashenweald",
      history: [],
    };

    const result = await SimulationAudit.execute_turn("Test input", scenario);

    expect(result.character_task).toContain("<SNAPSHOT>");
    expect(result.character_task).toContain("chaos=");
  });

  it("Pipeline verification passes all critical checks", async () => {
    const scenario = {
      ai_id: "silvers",
      user_id: "julien",
      fractal_id: "ashenweald",
      history: [],
    };

    const result = await SimulationAudit.execute_turn("Test input", scenario);

    expect(result.verification).toBeDefined();
    expect(result.verification.passed).toContain("character:task_has_EPISTEMIC_PHYSICS");
    expect(result.verification.passed).toContain("character:system_lacks_dynamics_attrs");
  });

  it("passes raw_messages for Director AI_LAST_TURN block", async () => {
    const scenario = {
      ai_id: "valerius",
      user_id: "caelum",
      fractal_id: "ashenweald",
      history: [{ role: "model", content: "The vampire lord smiles coldly.", character_name: "Lord Valerius" }],
    };

    const result = await SimulationAudit.execute_turn("I submit.", scenario);

    expect(result.director_task).toContain("<AI_CHARACTER_LAST_TURN>");
    expect(result.director_task).toContain("The vampire lord smiles coldly.");
  });
});
