/* ============================================================================
 * [GENERATED] src/theme/tokens.js
 * DO NOT EDIT DIRECTLY. Sync via 'npm run sync:design'.
 * ============================================================================ */

export const TOKENS = {
  "active-swatch-shadow": "0 0 var(--spacing-4) var(--signature-color)",
  "angle-right": "90deg",
  "angle-roll": "360deg",
  "angle-shimmy": "30deg",
  "angle-skew": "-20deg",
  "angle-spin": "90deg",
  "aspect-square": "1 / 1",
  "auto-resize-buffer": "var(--spacing-pixel)",
  "avatar-medium-size": "var(--columns-2)",
  "background-base": "var(--chalk)",
  "background-gradient-1": "#0b101a",
  "background-gradient-2": "#14182b",
  "background-gradient-3": "#1e1b38",
  "background-gradient-4": "#16243b",
  "blur-mist": "blur(var(--spacing-4))",
  "blur-void": "blur(var(--spacing-10))",
  "blur-whisper": "blur(var(--spacing-1))",
  "border-bottom": "var(--border-ghost)",
  "border-ghost": "var(--border-width-base) solid",
  "border-muted": "var(--border-width-base) solid",
  "border-side": "var(--border-whisper)",
  "border-top": "var(--border-muted)",
  "border-whisper": "var(--border-width-base) solid",
  "border-width-base": "var(--spacing-pixel)",
  "border-width-thick": "var(--spacing-1)",
  "box-height": "auto",
  "box-max-height": "calc(var(--spacing-20) * 5)",
  "breakpoint-desktop": "80rem",
  "breakpoint-mini": "30rem",
  "breakpoint-mobile": "48rem",
  "breakpoint-tablet": "64rem",
  "brightness-dim": "brightness(0.8)",
  "brightness-glow": "brightness(1.2)",
  "brightness-muted": "brightness(0.3)",
  "chalk": "#222326",
  "click-dim": "var(--brightness-dim)",
  "click-sink": "var(--scale-sink)",
  "column": "var(--column-unit)",
  "column-unit": "calc(var(--grid-width) / var(--column-units))",
  "column-units": "12",
  "columns-10": "calc(var(--column-unit) * 10)",
  "columns-11": "calc(var(--column-unit) * 11)",
  "columns-12": "calc(var(--column-unit) * 12)",
  "columns-2": "calc(var(--column-unit) * 2)",
  "columns-3": "calc(var(--column-unit) * 3)",
  "columns-4": "calc(var(--column-unit) * 4)",
  "columns-5": "calc(var(--column-unit) * 5)",
  "columns-6": "calc(var(--column-unit) * 6)",
  "columns-7": "calc(var(--column-unit) * 7)",
  "columns-8": "calc(var(--column-unit) * 8)",
  "columns-9": "calc(var(--column-unit) * 9)",
  "contrast-tension": "contrast(1.1)",
  "coral-rose": "#fb7185",
  "crimson-red": "#ef4444",
  "danger-color": "var(--crimson-red)",
  "danger-glow": "0 0 var(--spacing-3) var(--danger-color)",
  "danger-hover-shadow": "0 0 var(--spacing-4) rgb(from var(--crimson-red) r g b / var(--opacity-muted))",
  "deep-indigo": "#818cf8",
  "deep-z-index": "var(--z-index-below)",
  "dev-accent-default": "var(--frisk)",
  "dev-header-bg-active": "rgb(from var(--frisk) r g b / var(--opacity-ghost))",
  "dev-header-bg-dormant": "rgb(from var(--void-black) r g b / var(--opacity-muted))",
  "dev-header-height-active": "var(--spacing-6)",
  "dev-header-height-dormant": "var(--spacing-1)",
  "dropdown-max-height": "calc(var(--spacing-10) * 8)",
  "duration-atmospheric": "1500ms",
  "duration-fast": "250ms",
  "duration-none": "0s",
  "duration-pulse": "1000ms",
  "duration-reflex": "150ms",
  "duration-shimmer": "2500ms",
  "duration-slow": "500ms",
  "duration-standard": "350ms",
  "duration-tremor": "4s",
  "ease-elastic": "cubic-bezier(0.34, 1.56, 0.64, 1)",
  "ease-in": "cubic-bezier(0.4, 0, 1, 1)",
  "ease-out": "cubic-bezier(0, 0, 0.2, 1)",
  "ease-standard": "cubic-bezier(0.4, 0, 0.2, 1)",
  "electric-cyan": "#11aecc",
  "emerald-green": "#10b981",
  "entity-color": "var(--signature-color)",
  "floor-z-index": "var(--z-index-0)",
  "font-color-base": "var(--frisk)",
  "font-color-muted": "var(--frozen)",
  "font-family-base": "\"Inter\", system-ui, -apple-system, sans-serif",
  "font-family-heading": "\"Ubuntu\", sans-serif",
  "font-family-mono": "\"JetBrains Mono\", monospace",
  "font-height-base": "1.5",
  "font-height-s": "var(--font-height-short)",
  "font-height-short": "1.2",
  "font-height-tall": "1.8",
  "font-size-base": "clamp(0.9rem, 0.8vw + 0.8rem, 1.1rem)",
  "font-size-h1": "clamp(3rem, 5vw + 2rem, 6rem)",
  "font-size-h2": "clamp(2rem, 3vw + 1.5rem, 3.5rem)",
  "font-size-h3": "clamp(1.5rem, 2vw + 1.2rem, 2.5rem)",
  "font-size-h4": "clamp(1.25rem, 1.5vw + 1.1rem, 1.8rem)",
  "font-size-h5": "clamp(1.1rem, 1.2vw + 1rem, 1.5rem)",
  "font-size-h6": "clamp(1rem, 1vw + 0.9rem, 1.25rem)",
  "font-size-nano": "clamp(0.6rem, 0.3vw + 0.5rem, 0.7rem)",
  "font-size-small": "clamp(0.8rem, 0.6vw + 0.7rem, 0.95rem)",
  "font-size-tiny": "clamp(0.7rem, 0.5vw + 0.6rem, 0.8rem)",
  "font-spacing-base": "0em",
  "font-spacing-loose": "0.05em",
  "font-spacing-tight": "-0.02em",
  "font-spacing-wide": "0.1em",
  "font-spacing-wider": "0.12em",
  "font-weight-base": "400",
  "font-weight-bold": "700",
  "font-weight-heavy": "900",
  "font-weight-thin": "300",
  "forest-green": "#15803d",
  "frisk": "#f2f7fa",
  "frozen": "#555d66",
  "gap-loose": "var(--spacing-4)",
  "gap-standard": "var(--spacing-2)",
  "gap-tight": "var(--spacing-1)",
  "glass-base": "rgb(from var(--gunmetal) r g b / var(--opacity-muted))",
  "glass-base-blur": "var(--blur-whisper)",
  "glass-elevated": "rgb(from var(--frozen) r g b / var(--opacity-ghost))",
  "glass-elevated-blur": "var(--blur-mist)",
  "glass-peak": "rgb(from var(--pure-white) r g b / var(--opacity-muted))",
  "glass-peak-blur": "var(--blur-void)",
  "glass-sunken": "rgb(from var(--chalk) r g b / var(--opacity-muted))",
  "glass-sunken-blur": "var(--blur-whisper)",
  "golden-ratio": "1.618",
  "grid-height": "clamp(20rem, 100vh, var(--grid-height-max))",
  "grid-height-max": "clamp(25rem, calc(var(--golden-ratio) * 100vw), 100vh)",
  "grid-width": "clamp(var(--grid-width-min), 100vw, var(--grid-width-max))",
  "grid-width-max": "clamp(50rem, calc(var(--golden-ratio) * 100vh), 1800px)",
  "grid-width-min": "20rem",
  "gunmetal": "#363840",
  "hot-pink": "#ec4899",
  "hover-glow": "var(--brightness-glow)",
  "hover-lift": "var(--scale-lift)",
  "icon-large": "var(--spacing-8)",
  "icon-medium": "var(--spacing-5)",
  "icon-small": "var(--spacing-4)",
  "kinetic-drag-threshold": "10",
  "kinetic-momentum-friction": "0.95",
  "kinetic-scroll-multiplier": "1.5",
  "kinetic-shimmy-offset": "var(--kinetic-shimmy-tremor)",
  "kinetic-shimmy-tremor": "var(--spacing-pixel)",
  "kinetic-shimmy-y": "calc(var(--spacing-pixel) / 2)",
  "kinetic-slide-y": "calc(var(--spacing-pixel) * 10)",
  "kinetic-stab-distance": "var(--spacing-1)",
  "lemon-yellow": "#fde047",
  "lime-green": "#84cc16",
  "max-z-index": "var(--z-index-max)",
  "mid-z-index": "var(--z-index-50)",
  "modal-height-base": "var(--rows-6)",
  "modal-height-short": "var(--rows-4)",
  "modal-height-standard": "var(--rows-6)",
  "modal-height-tall": "var(--rows-8)",
  "modal-width-base": "var(--columns-6)",
  "modal-width-thin": "var(--columns-4)",
  "modal-width-wide": "var(--columns-8)",
  "modal-z-index": "var(--z-index-300)",
  "motion-dissolve": "opacity var(--duration-standard) var(--ease-standard)",
  "motion-elastic": "var(--duration-slow) var(--ease-elastic)",
  "motion-fast": "var(--duration-fast) var(--ease-standard)",
  "motion-slow": "var(--duration-slow) var(--ease-standard)",
  "motion-standard": "var(--duration-standard) var(--ease-standard)",
  "neon-teal": "#14b8a6",
  "noise-url": "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.65' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E\")",
  "ocean-blue": "#3b82f6",
  "opacity-base": "0.4",
  "opacity-ghost": "0.08",
  "opacity-half": "0.5",
  "opacity-heavy": "0.6",
  "opacity-intense": "0.9",
  "opacity-moderate": "0.7",
  "opacity-muted": "0.3",
  "opacity-noise": "0.03",
  "opacity-none": "0",
  "opacity-solid": "1",
  "opacity-substantial": "0.8",
  "opacity-whisper": "0.15",
  "overlay-peak-z-index": "var(--z-index-210)",
  "overlay-z-index": "var(--z-index-100)",
  "padding-loose": "var(--spacing-8)",
  "padding-standard": "var(--spacing-4)",
  "padding-tight": "var(--spacing-2)",
  "profile-fragment-column": "var(--spacing-24)",
  "profile-height": "var(--columns-4)",
  "profile-initials-size-base": "var(--spacing-40)",
  "profile-width": "var(--columns-6)",
  "pumpkin-amber": "#fbbf24",
  "pure-white": "#fff",
  "radius-full": "9999px",
  "radius-rounded": "var(--spacing-8)",
  "radius-sharp": "var(--spacing-1)",
  "radius-standard": "var(--spacing-4)",
  "radius-subtle": "var(--spacing-2)",
  "row": "var(--row-unit)",
  "row-unit": "calc(var(--grid-height) / var(--row-units))",
  "row-units": "12",
  "rows-10": "calc(var(--row-unit) * 10)",
  "rows-11": "calc(var(--row-unit) * 11)",
  "rows-12": "calc(var(--row-unit) * 12)",
  "rows-2": "calc(var(--row-unit) * 2)",
  "rows-3": "calc(var(--row-unit) * 3)",
  "rows-4": "calc(var(--row-unit) * 4)",
  "rows-5": "calc(var(--row-unit) * 5)",
  "rows-6": "calc(var(--row-unit) * 6)",
  "rows-7": "calc(var(--row-unit) * 7)",
  "rows-8": "calc(var(--row-unit) * 8)",
  "rows-9": "calc(var(--row-unit) * 9)",
  "royal-purple": "#a855f7",
  "saturation-tension": "saturate(1.2)",
  "scale-lift": "scale(1.02)",
  "scale-pulse-max": "scale(1.08)",
  "scale-pulse-mid": "scale(1.04)",
  "scale-sink": "scale(0.96)",
  "scale-tremor-high": "scale(1.002)",
  "scale-tremor-low": "scale(0.998)",
  "scale-tremor-mid": "scale(1.001)",
  "scale-zoom": "scale(1.1)",
  "scrollbar-thumb": "var(--gunmetal)",
  "scrollbar-thumb-hover": "var(--frisk)",
  "scrollbar-track": "transparent",
  "scrollbar-width": "var(--spacing-2)",
  "shadow-ambient": "var(--shadow-ghost)",
  "shadow-focus": "var(--shadow-heavy)",
  "shadow-font": "0 var(--spacing-pixel) var(--spacing-pixel) var(--void-black)",
  "shadow-ghost": "0 var(--spacing-pixel) var(--spacing-2px) rgb(from var(--void-black) r g b / var(--opacity-ghost))",
  "shadow-heavy": "0 var(--spacing-2) var(--spacing-8) rgb(from var(--void-black) r g b / var(--opacity-muted))",
  "shadow-light": "0 var(--spacing-1) var(--spacing-3) rgb(from var(--void-black) r g b / var(--opacity-whisper))",
  "signature-color": "var(--electric-cyan)",
  "signature-glow": "0 0 var(--spacing-4) var(--signature-color)",
  "skeleton-card-min-height": "var(--storyboard-character-card-height)",
  "skeleton-hero-min-height": "var(--spacing-60)",
  "skeleton-text-height": "1em",
  "skeleton-text-width": "60%",
  "slider-fill-color-end": "var(--gunmetal)",
  "slider-fill-color-start": "var(--frisk)",
  "slider-thumb-shadow": "0 0 var(--spacing-1) var(--pure-white), var(--shadow-ghost)",
  "slider-thumb-size": "var(--spacing-2)",
  "slider-track-height": "var(--spacing-1)",
  "spacing-0": 0,
  "spacing-1": "calc(var(--spacing-unit) * 1)",
  "spacing-10": "calc(var(--spacing-unit) * 10)",
  "spacing-12": "calc(var(--spacing-unit) * 12)",
  "spacing-15": "calc(var(--spacing-unit) * 15)",
  "spacing-16": "calc(var(--spacing-unit) * 16)",
  "spacing-2": "calc(var(--spacing-unit) * 2)",
  "spacing-20": "calc(var(--spacing-unit) * 20)",
  "spacing-24": "calc(var(--spacing-unit) * 24)",
  "spacing-2px": "2px",
  "spacing-3": "calc(var(--spacing-unit) * 3)",
  "spacing-30": "calc(var(--spacing-unit) * 30)",
  "spacing-4": "calc(var(--spacing-unit) * 4)",
  "spacing-40": "calc(var(--spacing-unit) * 40)",
  "spacing-5": "calc(var(--spacing-unit) * 5)",
  "spacing-6": "calc(var(--spacing-unit) * 6)",
  "spacing-60": "calc(var(--spacing-unit) * 60)",
  "spacing-8": "calc(var(--spacing-unit) * 8)",
  "spacing-9": "calc(var(--spacing-unit) * 9)",
  "spacing-pixel": "1px",
  "spacing-unit": "0.25rem",
  "state-accent": "var(--frisk)",
  "state-activity-color": "var(--neon-teal)",
  "state-align": "center",
  "state-dev-accent": "var(--frisk)",
  "state-fill-end": "100%",
  "state-fill-start": "0%",
  "state-intensity": "0",
  "state-metric-color": "var(--electric-cyan)",
  "state-metric-offset": "0%",
  "state-metric-span": "0%",
  "state-signature-color": "var(--electric-cyan)",
  "state-toggle-height": "var(--toggle-height)",
  "state-toggle-thumb-offset": "var(--toggle-thumb-offset)",
  "state-toggle-thumb-size": "var(--toggle-thumb-size)",
  "state-toggle-width": "var(--toggle-width)",
  "state-value": "0%",
  "state-weight": "0",
  "state-weight-intensity": "0",
  "storyboard-character-card-height": "var(--rows-6)",
  "storyboard-character-card-width": "var(--columns-2)",
  "storyboard-fractal-card-height": "var(--rows-4)",
  "storyboard-fractal-card-width": "var(--columns-4)",
  "sunset-orange": "#f97316",
  "surface-peak-z-index": "var(--z-index-20)",
  "surface-z-index": "var(--z-index-10)",
  "swatch-color": "var(--signature-color)",
  "swatch-dynamic-bg": "var(--gunmetal)",
  "title-color-part": "var(--frozen)",
  "title-glow-signature": "0 0 var(--spacing-5) var(--signature-color)",
  "title-shadow-ambient": "0 0 var(--spacing-5)",
  "title-shadow-focus": "0 0 0 var(--spacing-pixel) var(--frisk)",
  "toast-z-index": "var(--z-index-1000)",
  "toggle-height": "var(--font-size-h5)",
  "toggle-small-height": "var(--spacing-4)",
  "toggle-small-thumb-size": "var(--font-size-small)",
  "toggle-small-width": "calc(var(--spacing-8) + var(--spacing-1))",
  "toggle-thumb-offset": "calc((var(--toggle-height) - var(--toggle-thumb-size)) / 2)",
  "toggle-thumb-size": "var(--spacing-4)",
  "toggle-width": "calc(var(--spacing-12) + var(--spacing-2))",
  "twilight-violet": "#c084fc",
  "void-black": "#000",
  "width-sidebar": "var(--columns-2)",
  "wing-width": "var(--columns-2)",
  "z-index-0": "0",
  "z-index-10": "10",
  "z-index-100": "100",
  "z-index-1000": "1000",
  "z-index-20": "20",
  "z-index-200": "200",
  "z-index-210": "210",
  "z-index-300": "300",
  "z-index-50": "50",
  "z-index-below": "-1",
  "z-index-max": "9999"
};

export const PALETTE = {
  "Background Gradient 1": "#0b101a",
  "Background Gradient 2": "#14182b",
  "Background Gradient 3": "#1e1b38",
  "Background Gradient 4": "#16243b",
  "Chalk": "#222326",
  "Coral Rose": "#fb7185",
  "Crimson Red": "#ef4444",
  "Deep Indigo": "#818cf8",
  "Electric Cyan": "#11aecc",
  "Emerald Green": "#10b981",
  "Forest Green": "#15803d",
  "Frisk": "#f2f7fa",
  "Frozen": "#555d66",
  "Gunmetal": "#363840",
  "Hot Pink": "#ec4899",
  "Lemon Yellow": "#fde047",
  "Lime Green": "#84cc16",
  "Neon Teal": "#14b8a6",
  "Ocean Blue": "#3b82f6",
  "Pumpkin Amber": "#fbbf24",
  "Pure White": "#fff",
  "Royal Purple": "#a855f7",
  "Sunset Orange": "#f97316",
  "Twilight Violet": "#c084fc",
  "Void Black": "#000"
};

export const PALETTE_VARS = {
  "#0b101a": "var(--background-gradient-1)",
  "#14182b": "var(--background-gradient-2)",
  "#1e1b38": "var(--background-gradient-3)",
  "#16243b": "var(--background-gradient-4)",
  "#222326": "var(--chalk)",
  "#fb7185": "var(--coral-rose)",
  "#ef4444": "var(--crimson-red)",
  "#818cf8": "var(--deep-indigo)",
  "#11aecc": "var(--electric-cyan)",
  "#10b981": "var(--emerald-green)",
  "#15803d": "var(--forest-green)",
  "#f2f7fa": "var(--frisk)",
  "#555d66": "var(--frozen)",
  "#363840": "var(--gunmetal)",
  "#ec4899": "var(--hot-pink)",
  "#fde047": "var(--lemon-yellow)",
  "#84cc16": "var(--lime-green)",
  "#14b8a6": "var(--neon-teal)",
  "#3b82f6": "var(--ocean-blue)",
  "#fbbf24": "var(--pumpkin-amber)",
  "#fff": "var(--pure-white)",
  "#a855f7": "var(--royal-purple)",
  "#f97316": "var(--sunset-orange)",
  "#c084fc": "var(--twilight-violet)",
  "#000": "var(--void-black)"
};
