/**
 * validation.js - Central validation and sanitization module
 * Single source of truth for all data validation in RPGlitch.
 *
 * @module validation
 */

import { log, error } from "./utils.js";

/**
 * Valid image file extensions.
 * Covers common web formats and some legacy formats.
 */
const VALID_IMAGE_EXTENSIONS = [
  "jpg",
  "jpeg",
  "png",
  "gif",
  "webp",
  "svg",
  "bmp",
  "tiff",
  "tif",
  "ico",
  "avif",
  "jfif",
];

/**
 * Valid URL protocols for image sources.
 * Includes data URLs for inline images and blob URLs for file uploads.
 */
const VALID_PROTOCOLS = ["https:", "http:", "blob:", "data:"];

/**
 * Regex pattern to match valid image file extensions in URLs.
 * Case-insensitive, allows query parameters after extension.
 */
const IMAGE_EXTENSION_REGEX = new RegExp(
  `\\.(${VALID_IMAGE_EXTENSIONS.join("|")})(\\?.*)?$`,
  "i"
);

/**
 * Signature color palette constants.
 * Matches SCSS variables in _foundation.scss
 *
 * @constant {Object.<string, string>}
 */
export const SIGNATURE_COLORS = {
  pink: "#ec4899",
  emerald: "#10b981",
  cyan: "#06b6d4",
  orange: "#f97316",
  purple: "#a855f7",
  default: "#777",
};

/**
 * Validates image URL format and security.
 *
 * Performs comprehensive validation:
 * - Type checking (must be string, minimum length 5)
 * - URL format validation (must parse as valid URL)
 * - Protocol whitelist (https, http, blob, data only)
 * - Data URL format validation (must be data:image/*)
 * - File extension validation for http/https URLs
 *
 * @param {string} urlString - URL to validate
 * @param {boolean} [allowLog=false] - Enable console logging for debugging
 * @returns {boolean} True if valid image URL
 */
export function isValidImageUrl(urlString, allowLog = false) {
  // Type and length validation
  if (typeof urlString !== "string" || urlString.length < 5) {
    return false;
  }

  try {
    const urlObj = new URL(urlString);

    // Protocol validation - security critical
    if (!VALID_PROTOCOLS.includes(urlObj.protocol)) {
      if (allowLog) {
        log("[Validation] Invalid protocol:", urlObj.protocol);
      }
      return false;
    }

    // Data URL validation - must be image MIME type
    if (urlObj.protocol === "data:") {
      const isImageDataUrl = urlString.startsWith("data:image/");
      if (!isImageDataUrl && allowLog) {
        log("[Validation] Data URL must be image/* MIME type");
      }
      return isImageDataUrl;
    }

    // Blob URL validation - always valid (generated by browser)
    if (urlObj.protocol === "blob:") {
      return true;
    }

    // Extension validation for http/https URLs
    const hasValidExtension = IMAGE_EXTENSION_REGEX.test(urlObj.pathname);
    if (!hasValidExtension && allowLog) {
      log(
        "[Validation] Missing or invalid image extension in:",
        urlObj.pathname
      );
    }
    return hasValidExtension;
  } catch (error) {
    if (allowLog) {
      log("[Validation] URL parse error:", error.message);
    }
    return false;
  }
}

/**
 * Extracts image URL from plugin response.
 *
 * Supports 5 active plugin formats:
 * 1. text-to-image standard: { imageUrl: "..." }
 * 2. text-to-image data URL: { dataUrl: "..." }
 * 3. upload plugin: { url: "..." }
 * 4. text-to-image ID (legacy): { imageId: "...", fileExtension: "..." }
 * 5. Legacy fallback: direct string (last resort)
 *
 * @param {*} result - Plugin response (object or string)
 * @returns {string|undefined} Extracted URL or undefined if not found
 */
export function extractImageUrl(result) {
  let url;

  // Format 1: text-to-image standard
  if (result?.imageUrl && typeof result.imageUrl === "string") {
    url = result.imageUrl;
  }
  // Format 2: text-to-image data URL
  else if (result?.dataUrl && typeof result.dataUrl === "string") {
    url = result.dataUrl;
  }
  // Format 3: upload plugin
  else if (result?.url) {
    url = String(result.url);
  }
  // Format 4: Legacy/Alternative text-to-image (imageId + fileExtension)
  else if (result?.imageId && result?.fileExtension) {
    url = `https://img.perchance.org/${result.imageId}.${result.fileExtension}`;
  }
  // Format 5: Legacy fallback - direct string (last resort)
  else if (typeof result === "string") {
    url = result;
  }

  // Trim whitespace and reject empty strings
  if (typeof url === "string") {
    url = url.trim();
    return url === "" ? undefined : url;
  }

  return undefined;
}

/**
 * Sanitizes HTML content using DOMPurify.
 * * 🔴 SECURITY CRITICAL: This function Fails Closed.
 * If DOMPurify is not available, it throws an error rather than
 * returning potentially unsafe content.
 *
 * @param {string} html - HTML to sanitize
 * @returns {string} Sanitized HTML safe for innerHTML
 * @throws {Error} If DOMPurify is missing
 */
export function sanitizeHtml(html) {
  const value = typeof html === "string" ? html : String(html ?? "");

  // ZERO TRUST: We do not allow execution without the sanitizer.
  if (typeof window === "undefined" || !window.DOMPurify) {
    const msg = "Security Error: DOMPurify not loaded. Cannot sanitize content.";
    error(msg);
    throw new Error(msg);
  }

  try {
    return window.DOMPurify.sanitize(value);
  } catch (err) {
    error("Sanitization failed:", err);
    return ""; // Fail safe to empty string on processing error
  }
}

/**
 * Validates and returns a signature color value.
 *
 * @param {string} colorKey - Color key (pink, emerald, cyan, orange, purple, default)
 * @returns {string} Valid hex color code
 */
export function getSignatureColor(colorKey) {
  return SIGNATURE_COLORS[colorKey] || SIGNATURE_COLORS.default;
}

/**
 * Calculates contrast color (black or white) for a given background color.
 *
 * @param {string} hexColor - Hex color code (e.g., '#ec4899' or '#f00')
 * @returns {string} '#000' for light backgrounds, '#fff' for dark backgrounds
 */
export function getContrastColor(hexColor) {
  // Input validation
  if (typeof hexColor !== "string" || !hexColor) {
    return "#000";
  }

  // Remove # if present
  let hex = hexColor.replace("#", "");

  // Handle 3-digit hex shorthand (e.g., #fff -> #ffffff)
  if (hex.length === 3) {
    hex = hex
      .split("")
      .map((char) => char + char)
      .join("");
  }

  // Validate hex length
  if (hex.length !== 6) {
    return "#000"; // Return default for invalid input
  }

  // Parse RGB components
  const r = parseInt(hex.substring(0, 2), 16);
  const g = parseInt(hex.substring(2, 4), 16);
  const b = parseInt(hex.substring(4, 6), 16);

  // Check for invalid hex characters resulting in NaN
  if (isNaN(r) || isNaN(g) || isNaN(b)) {
    return "#000"; // Return default for invalid input
  }

  // Calculate luminance using YIQ coefficients (common approximation)
  const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;

  // Return black for light backgrounds, white for dark backgrounds
  return luminance > 0.5 ? "#000" : "#fff";
}