/**
 * validation.js - Central validation and sanitization module
 * Single source of truth for all data validation in RPGlitch.
 *
 * @module validation
 */

import DOMPurify from 'dompurify';

/**
 * Valid image file extensions.
 * Covers common web formats and some legacy formats.
 */
const VALID_IMAGE_EXTENSIONS = [
  'jpg', 'jpeg', 'png', 'gif', 'webp',
  'svg', 'bmp', 'tiff', 'tif', 'ico',
  'avif', 'jfif'
];

/**
 * Valid URL protocols for image sources.
 * Includes data URLs for inline images and blob URLs for file uploads.
 */
const VALID_PROTOCOLS = ['https:', 'http:', 'blob:', 'data:'];

/**
 * Regex pattern to match valid image file extensions in URLs.
 * Case-insensitive, allows query parameters after extension.
 */
const IMAGE_EXTENSION_REGEX = new RegExp(
  `\\.(${VALID_IMAGE_EXTENSIONS.join('|')})(\\?.*)?$`,
  'i'
);

/**
 * Signature color palette constants.
 * Matches SCSS variables in _foundation.scss
 *
 * @constant {Object.<string, string>}
 */
export const SIGNATURE_COLORS = {
  pink: '#ec4899',
  emerald: '#10b981',
  cyan: '#06b6d4',
  orange: '#f97316',
  purple: '#a855f7',
  default: '#777'
};

/**
 * Validates image URL format and security.
 *
 * Performs comprehensive validation:
 * - Type checking (must be string, minimum length 5)
 * - URL format validation (must parse as valid URL)
 * - Protocol whitelist (https, http, blob, data only)
 * - Data URL format validation (must be data:image/*)
 * - File extension validation for http/https URLs
 *
 * @param {string} urlString - URL to validate
 * @param {boolean} [allowLog=false] - Enable console logging for debugging
 * @returns {boolean} True if valid image URL
 *
 * @example
 * isValidImageUrl('https://example.com/image.jpg') // true
 * isValidImageUrl('data:image/png;base64,...') // true
 * isValidImageUrl('blob:http://localhost/...') // true
 * isValidImageUrl('ftp://example.com/image.jpg') // false (invalid protocol)
 * isValidImageUrl('https://example.com/doc.pdf') // false (invalid extension)
 */
export function isValidImageUrl(urlString, allowLog = false) {
  // Type and length validation
  if (typeof urlString !== 'string' || urlString.length < 5) {
    return false;
  }

  try {
    const urlObj = new URL(urlString);

    // Protocol validation - security critical
    if (!VALID_PROTOCOLS.includes(urlObj.protocol)) {
      if (allowLog) {
        console.warn('[Validation] Invalid protocol:', urlObj.protocol);
      }
      return false;
    }

    // Data URL validation - must be image MIME type
    if (urlObj.protocol === 'data:') {
      const isImageDataUrl = urlString.startsWith('data:image/');
      if (!isImageDataUrl && allowLog) {
        console.warn('[Validation] Data URL must be image/* MIME type');
      }
      return isImageDataUrl;
    }

    // Blob URL validation - always valid (generated by browser)
    if (urlObj.protocol === 'blob:') {
      return true;
    }

    // Extension validation for http/https URLs
    const hasValidExtension = IMAGE_EXTENSION_REGEX.test(urlObj.pathname);
    if (!hasValidExtension && allowLog) {
      console.warn('[Validation] Missing or invalid image extension in:', urlObj.pathname);
    }
    return hasValidExtension;

  } catch (error) {
    if (allowLog) {
      console.warn('[Validation] URL parse error:', error.message);
    }
    return false;
  }
}

/**
 * Extracts image URL from plugin response.
 *
 * Supports 4 active plugin formats:
 * 1. text-to-image standard: { imageUrl: "..." }
 * 2. text-to-image data URL: { dataUrl: "..." }
 * 3. upload plugin: { url: "..." }
 * 4. Legacy fallback: direct string (last resort)
 *
 * Does NOT support deprecated formats:
 * - { imageId, fileExtension } (old text-to-image)
 * - { file: { url } } (nested upload)
 * - { file: "..." } (direct file)
 * - { name: "..." } (unusual fallback)
 * - { value: "..." } (generic fallback)
 *
 * @param {*} result - Plugin response (object or string)
 * @returns {string|undefined} Extracted URL or undefined if not found
 *
 * @example
 * extractImageUrl({ imageUrl: 'https://...' }) // 'https://...'
 * extractImageUrl({ dataUrl: 'data:image/...' }) // 'data:image/...'
 * extractImageUrl({ url: 'blob:...' }) // 'blob:...'
 * extractImageUrl('https://...') // 'https://...' (legacy)
 * extractImageUrl({ imageId: '123' }) // undefined (deprecated format)
 */
export function extractImageUrl(result) {
  let url;

  // Format 1: text-to-image standard
  if (result?.imageUrl && typeof result.imageUrl === 'string') {
    url = result.imageUrl;
  }
  // Format 2: text-to-image data URL
  else if (result?.dataUrl && typeof result.dataUrl === 'string') {
    url = result.dataUrl;
  }
  // Format 3: upload plugin
  else if (result?.url) {
    url = String(result.url);
  }
  // Format 4: Legacy fallback - direct string (last resort)
  else if (typeof result === 'string') {
    url = result;
  }

  // Trim whitespace and reject empty strings
  if (typeof url === 'string') {
    url = url.trim();
    return url === '' ? undefined : url;
  }

  return undefined;
}

/**
 * Sanitizes HTML content using DOMPurify.
 *
 * Removes potentially dangerous HTML/JavaScript:
 * - Script tags and event handlers
 * - Dangerous attributes (onclick, onerror, etc.)
 * - JavaScript: protocol links
 * - Other XSS vectors
 *
 * @param {string} html - HTML to sanitize
 * @returns {string} Sanitized HTML safe for innerHTML
 *
 * @example
 * sanitizeHtml('<p>Hello</p>') // '<p>Hello</p>'
 * sanitizeHtml('<script>alert("XSS")</script>') // ''
 * sanitizeHtml('<img src=x onerror=alert(1)>') // '<img src="x">'
 */
export function sanitizeHtml(html) {
  const value = typeof html === 'string' ? html : String(html ?? '');
  try {
    return DOMPurify ? DOMPurify.sanitize(value) : value;
  } catch {
    return value;
  }
}

/**
 * Validates and returns a signature color value.
 *
 * @param {string} colorKey - Color key (pink, emerald, cyan, orange, purple, default)
 * @returns {string} Valid hex color code
 *
 * @example
 * getSignatureColor('pink') // '#ec4899'
 * getSignatureColor('invalid') // '#777' (default)
 */
export function getSignatureColor(colorKey) {
  return SIGNATURE_COLORS[colorKey] || SIGNATURE_COLORS.default;
}

/**
 * Calculates contrast color (black or white) for a given background color.
 *
 * Uses luminance calculation with YIQ coefficients (common approximation).
 * Handles both 6-digit (#rrggbb) and 3-digit (#rgb) hex formats.
 *
 * @param {string} hexColor - Hex color code (e.g., '#ec4899' or '#f00')
 * @returns {string} '#000' for light backgrounds, '#fff' for dark backgrounds
 *
 * @example
 * getContrastColor('#ec4899') // '#fff' (pink is dark enough)
 * getContrastColor('#10b981') // '#000' (emerald is too light)
 * getContrastColor('#fff') // '#000' (white background needs black text)
 * getContrastColor('invalid') // '#000' (fallback for invalid input)
 */
export function getContrastColor(hexColor) {
  // Input validation
  if (typeof hexColor !== 'string' || !hexColor) {
    return '#000';
  }

  // Remove # if present
  let hex = hexColor.replace('#', '');

  // Handle 3-digit hex shorthand (e.g., #fff -> #ffffff)
  if (hex.length === 3) {
    hex = hex.split('').map(char => char + char).join('');
  }

  // Validate hex length
  if (hex.length !== 6) {
    return '#000'; // Return default for invalid input
  }

  // Parse RGB components
  const r = parseInt(hex.substring(0, 2), 16);
  const g = parseInt(hex.substring(2, 4), 16);
  const b = parseInt(hex.substring(4, 6), 16);

  // Check for invalid hex characters resulting in NaN
  if (isNaN(r) || isNaN(g) || isNaN(b)) {
    return '#000'; // Return default for invalid input
  }

  // Calculate luminance using YIQ coefficients (common approximation)
  const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;

  // Return black for light backgrounds, white for dark backgrounds
  return luminance > 0.5 ? '#000' : '#fff';
}
