/* ============================================================================
 * [GENERATED] src/media/tokens.js
 * DO NOT EDIT DIRECTLY. Sovereign Source: DESIGN.md.
 * ============================================================================ */

export const TOKENS = {
  "background-gradient-1": "#0b101a",
  "background-gradient-2": "#14182b",
  "background-gradient-3": "#1e1b38",
  "background-gradient-4": "#16243b",
  chalk: "#171717",
  "coral-rose": "#fb7185",
  "crimson-red": "#ef4444",
  "danger-color": "var(--crimson-red)",
  "deep-indigo": "#818cf8",
  "electric-cyan": "#11aecc",
  "emerald-green": "#10b981",
  "font-color-base": "var(--frisk)",
  "font-color-muted": "var(--frozen)",
  "forest-green": "#15803d",
  frisk: "#f8fafc",
  frozen: "#475569",
  "glass-base": "rgb(from var(--gunmetal) r g b / var(--opacity-muted))",
  "glass-elevated": "rgb(from var(--frozen) r g b / var(--opacity-whisper))",
  "glass-peak": "rgb(from var(--pure-white) r g b / var(--opacity-muted))",
  "glass-sunken": "rgb(from var(--chalk) r g b / var(--opacity-muted))",
  gunmetal: "#334155",
  "hot-pink": "#ec4899",
  "lemon-yellow": "#fde047",
  "lime-green": "#84cc16",
  "neon-teal": "#14b8a6",
  "ocean-blue": "#3b82f6",
  "pumpkin-amber": "#fbbf24",
  "pure-white": "#fff",
  "royal-purple": "#a855f7",
  "signature-color": "var(--frozen)",
  "slider-fill-color-end": "var(--gunmetal)",
  "slider-fill-color-start": "var(--frisk)",
  "state-activity-color": "var(--frozen)",
  "state-metric-color": "var(--frozen)",
  "state-signature-color": "var(--frozen)",
  "sunset-orange": "#f97316",
  "swatch-color": "var(--signature-color)",
  "title-color-part": "var(--frozen)",
  "twilight-violet": "#c084fc",
  "void-black": "#000",
  "font-family-base": '"Inter", system-ui, -apple-system, sans-serif',
  "font-family-heading": '"Ubuntu", sans-serif',
  "font-family-mono": '"JetBrains Mono", monospace',
  "font-height-base": "1.5",
  "font-height-tall": "1.8",
  "font-size-base": "clamp(0.9rem, 0.8vw + 0.8rem, 1.1rem)",
  "font-size-h1": "clamp(3rem, 5vw + 2rem, 6rem)",
  "font-size-h2": "clamp(2.8rem, 4.5vw + 2.2rem, 4.8rem)",
  "font-size-h3": "clamp(2rem, 3vw + 1.6rem, 3.2rem)",
  "font-size-h4": "clamp(1.6rem, 2vw + 1.4rem, 2.4rem)",
  "font-size-h5": "clamp(1.1rem, 1.2vw + 1rem, 1.5rem)",
  "font-size-h6": "clamp(1rem, 1vw + 0.9rem, 1.25rem)",
  "font-size-nano": "clamp(0.6rem, 0.3vw + 0.5rem, 0.7rem)",
  "font-size-small": "clamp(0.8rem, 0.6vw + 0.7rem, 0.95rem)",
  "font-size-tiny": "clamp(0.7rem, 0.5vw + 0.6rem, 0.8rem)",
  "font-spacing-base": "0em",
  "font-spacing-loose": "0.05em",
  "font-spacing-tight": "-0.05em",
  "font-weight-base": "400",
  "font-weight-bold": "800",
  "font-weight-thin": "300",
  "radius-full": "9999px",
  "radius-rounded": "calc(var(--spacing-unit) * 8)",
  "radius-sharp": "var(--spacing-unit)",
  "radius-standard": "calc(var(--spacing-unit) * 4)",
  "auto-resize-buffer": "var(--spacing-pixel)",
  "column-unit": "calc(var(--grid-width) / 12)",
  "gap-loose": "calc(var(--spacing-unit) * 6)",
  "gap-standard": "calc(var(--spacing-unit) * 4)",
  "gap-tight": "calc(var(--spacing-unit) * 2)",
  "grid-height": "clamp(20rem, 100vh, var(--grid-height-max))",
  "grid-height-max": "clamp(25rem, calc(var(--golden-ratio) * 100vw), 100vh)",
  "grid-width": "clamp(20rem, 100vw, var(--grid-width-max))",
  "grid-width-max": "clamp(50rem, calc(var(--golden-ratio) * 100vh), 100vw)",
  "margin-loose": "calc(var(--spacing-unit) * 8)",
  "margin-standard": "calc(var(--spacing-unit) * 4)",
  "margin-tight": "calc(var(--spacing-unit) * 2)",
  "padding-loose": "calc(var(--spacing-unit) * 8)",
  "padding-standard": "calc(var(--spacing-unit) * 4)",
  "padding-tight": "calc(var(--spacing-unit) * 2)",
  "row-unit": "calc(var(--grid-height) / 12)",
  "spacing-pixel": "1px",
  "spacing-unit": "0.25rem",
  "active-swatch-shadow": "0 0 calc(var(--spacing-unit) * 4) var(--signature-color)",
  "aspect-square": "1 / 1",
  "avatar-medium-size": "calc(var(--column-unit) * 2)",
  "blur-mist": "blur(calc(var(--spacing-unit) * 4))",
  "blur-void": "blur(calc(var(--spacing-unit) * 10))",
  "blur-whisper": "blur(var(--spacing-unit))",
  "border-ghost": "var(--border-width-base) solid var(--opacity-ghost)",
  "border-muted": "var(--border-width-base) solid var(--opacity-muted)",
  "border-whisper": "var(--border-width-base) solid var(--opacity-whisper)",
  "border-width-base": "var(--spacing-pixel)",
  "border-width-thick": "var(--spacing-unit)",
  "box-height": "auto",
  "box-max-height": "calc(var(--spacing-unit) * 100)",
  "breakpoint-desktop": "80rem",
  "breakpoint-high-density": "120rem",
  "breakpoint-mini": "30rem",
  "breakpoint-mobile": "48rem",
  "breakpoint-tablet": "64rem",
  "brightness-dim": "brightness(0.9)",
  "brightness-glow": "brightness(1.1)",
  "brightness-muted": "brightness(0.3)",
  "card-title-max-height": "2.4em",
  "danger-glow": "0 0 calc(var(--spacing-unit) * 3) var(--crimson-red)",
  "danger-hover-shadow":
    "0 0 calc(var(--spacing-unit) * 4)\nrgb(from var(--crimson-red) r g b / var(--opacity-muted))",
  "dev-accent": "var(--electric-cyan)",
  "dev-accent-default": "var(--frisk)",
  "dev-header-height-active": "calc(var(--spacing-unit) * 6)",
  "dev-header-height-dormant": "calc(var(--spacing-unit) * 2)",
  "dropdown-max-height": "calc(var(--spacing-unit) * 80)",
  "duration-ambient": "2000ms",
  "duration-fast": "150ms",
  "duration-none": "0s",
  "duration-slow": "500ms",
  "duration-standard": "300ms",
  "ease-elastic": "ease-out",
  "ease-in": "cubic-bezier(0.4, 0, 1, 1)",
  "ease-out": "cubic-bezier(0, 0, 0.2, 1)",
  "ease-standard": "cubic-bezier(0.4, 0, 0.2, 1)",
  "golden-ratio": "1.618",
  "icon-giant": "calc(var(--spacing-unit) * 20)",
  "icon-large": "calc(var(--spacing-unit) * 12)",
  "icon-medium": "calc(var(--spacing-unit) * 8)",
  "icon-small": "calc(var(--spacing-unit) * 4)",
  "kinetic-drag-threshold": "10",
  "kinetic-momentum-friction": "0.95",
  "kinetic-scroll-multiplier": "1.5",
  "kinetic-shimmy-offset": "var(--spacing-pixel)",
  "kinetic-shimmy-y": "calc(var(--spacing-pixel) / 2)",
  "kinetic-slide-y": "calc(var(--spacing-pixel) * 10)",
  "kinetic-stab-distance": "var(--spacing-unit)",
  "modal-height-short": "calc(var(--row-unit) * 3)",
  "modal-height-standard": "calc(var(--row-unit) * 6)",
  "modal-height-tall": "calc(var(--row-unit) * 9)",
  "modal-width-base": "calc(var(--column-unit) * 6)",
  "modal-width-thin": "calc(var(--column-unit) * 3)",
  "modal-width-wide": "calc(var(--column-unit) * 9)",
  "motion-dissolve": "opacity var(--duration-standard) var(--ease-standard)",
  "motion-elastic": "var(--duration-slow) var(--ease-elastic)",
  "motion-fast": "var(--duration-fast) var(--ease-standard)",
  "motion-slow": "var(--duration-slow) var(--ease-standard)",
  "motion-standard": "var(--duration-standard) var(--ease-standard)",
  "noise-url":
    "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.65' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E\")",
  "opacity-ghost": "0.1",
  "opacity-muted": "0.6",
  "opacity-none": "0",
  "opacity-solid": "1",
  "opacity-whisper": "0.3",
  "scale-lift": "scale(1.02)",
  "scale-pulse": "scale(1.05)",
  "scale-sink": "scale(0.96)",
  "scan-animation": "scan var(--duration-ambient) linear infinite",
  "scrollbar-thumb": "var(--gunmetal)",
  "scrollbar-thumb-hover": "var(--frisk)",
  "scrollbar-track": "transparent",
  "scrollbar-width": "calc(var(--spacing-unit) * 2)",
  "shadow-ambient": "var(--shadow-ghost)",
  "shadow-font": "0 var(--spacing-pixel) var(--spacing-pixel) var(--void-black)",
  "shadow-ghost":
    "0 var(--spacing-pixel) var(--spacing-pixel)\nrgb(from var(--void-black) r g b / var(--opacity-ghost))",
  "shadow-standard":
    "0 var(--spacing-unit) calc(var(--spacing-unit) * 4)\nrgb(from var(--void-black) r g b / var(--opacity-whisper))",
  "signature-glow": "0 0 calc(var(--spacing-unit) * 4) var(--signature-color)",
  "slider-thumb-shadow": "0 0 var(--spacing-unit) var(--pure-white), var(--shadow-ghost)",
  "slider-thumb-size": "calc(var(--spacing-unit) * 2)",
  "slider-track-height": "var(--spacing-unit)",
  "spring-damping-default": "0.8",
  "spring-stiffness-default": "0.15",
  "state-accent": "var(--frisk)",
  "state-align": "center",
  "state-dev-accent": "var(--frisk)",
  "state-fill-end": "100%",
  "state-fill-start": "0%",
  "state-intensity": "0",
  "state-metric-offset": "0%",
  "state-metric-span": "0%",
  "state-toggle-height": "var(--toggle-height)",
  "state-toggle-thumb-offset": "var(--toggle-thumb-offset)",
  "state-toggle-thumb-size": "var(--toggle-thumb-size)",
  "state-toggle-width": "var(--toggle-width)",
  "state-value": "0%",
  "state-weight": "0",
  "state-weight-intensity": "0",
  "storyboard-character-card-height": "calc(var(--row-unit) * 5)",
  "storyboard-character-card-width": "calc(var(--column-unit) * 2)",
  "storyboard-fractal-card-height": "calc(var(--row-unit) * 4)",
  "storyboard-fractal-card-width": "calc(var(--column-unit) * 4)",
  "swatch-dynamic-bg": "var(--gunmetal)",
  "title-glow-signature": "0 0 calc(var(--spacing-unit) * 5) var(--signature-color)",
  "title-shadow-ambient": "0 0 calc(var(--spacing-unit) * 5) var(--void-black)",
  "title-shadow-focus": "0 0 0 var(--spacing-pixel) var(--frisk)",
  "toggle-height": "var(--font-size-h5)",
  "toggle-small-height": "calc(var(--spacing-unit) * 4)",
  "toggle-small-thumb-size": "var(--font-size-small)",
  "toggle-small-width": "calc(var(--spacing-unit) * 9)",
  "toggle-thumb-offset": "calc((var(--toggle-height) - var(--toggle-thumb-size)) / 2)",
  "toggle-thumb-size": "calc(var(--spacing-unit) * 4)",
  "toggle-width": "calc(var(--spacing-unit) * 14)",
  "width-sidebar": "calc(var(--column-unit) * 2)",
  "z-index-base": "0",
  "z-index-below": "-1",
  "z-index-elevated": "50",
  "z-index-max": "999",
  "z-index-modal": "300",
  "z-index-overlay": "100",
  "z-index-surface": "10",
};

export const PALETTE = {
  "Background Gradient 1": "#0b101a",
  "Background Gradient 2": "#14182b",
  "Background Gradient 3": "#1e1b38",
  "Background Gradient 4": "#16243b",
  Chalk: "#171717",
  "Coral Rose": "#fb7185",
  "Crimson Red": "#ef4444",
  "Deep Indigo": "#818cf8",
  "Electric Cyan": "#11aecc",
  "Emerald Green": "#10b981",
  "Forest Green": "#15803d",
  Frisk: "#f8fafc",
  Frozen: "#475569",
  Gunmetal: "#334155",
  "Hot Pink": "#ec4899",
  "Lemon Yellow": "#fde047",
  "Lime Green": "#84cc16",
  "Neon Teal": "#14b8a6",
  "Ocean Blue": "#3b82f6",
  "Pumpkin Amber": "#fbbf24",
  "Pure White": "#fff",
  "Royal Purple": "#a855f7",
  "Sunset Orange": "#f97316",
  "Twilight Violet": "#c084fc",
  "Void Black": "#000",
};

export const PALETTE_VARS = {
  "#0b101a": "var(--background-gradient-1)",
  "#14182b": "var(--background-gradient-2)",
  "#1e1b38": "var(--background-gradient-3)",
  "#16243b": "var(--background-gradient-4)",
  "#171717": "var(--chalk)",
  "#fb7185": "var(--coral-rose)",
  "#ef4444": "var(--crimson-red)",
  "#818cf8": "var(--deep-indigo)",
  "#11aecc": "var(--electric-cyan)",
  "#10b981": "var(--emerald-green)",
  "#15803d": "var(--forest-green)",
  "#f8fafc": "var(--frisk)",
  "#475569": "var(--frozen)",
  "#334155": "var(--gunmetal)",
  "#ec4899": "var(--hot-pink)",
  "#fde047": "var(--lemon-yellow)",
  "#84cc16": "var(--lime-green)",
  "#14b8a6": "var(--neon-teal)",
  "#3b82f6": "var(--ocean-blue)",
  "#fbbf24": "var(--pumpkin-amber)",
  "#fff": "var(--pure-white)",
  "#a855f7": "var(--royal-purple)",
  "#f97316": "var(--sunset-orange)",
  "#c084fc": "var(--twilight-violet)",
  "#000": "var(--void-black)",
};
